### ISSUE TITLE
No more "override" exception?

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/Steam-MarketableApps#1]
*The Vanishing of Ethan Carter VR* is a DLC with its own (marketable) trading cards, which appears in your "override" file.

https://github.com/Citrinate/Steam-MarketableApps/blob/d8a8b11ef65ed217aa1b6360ea19004a44fa7543/overrides/marketable_app_overrides.json#L1-L3

For info, it is going to [be removed at the end of May 2024](https://store.steampowered.com/news/app/457880/view/4174352435309427467).

![Picture](https://i.imgur.com/rEXdvO4.png)

This likely means that the trading cards would turn unmarketable, and thus that there would be no need for any "override" exception anymore.

---

**References**:

- base game: https://www.steamcardexchange.net/index.php?gamepage-appid-258520/

![Base game](https://i.imgur.com/DbWBWvy.png)

- DLC: https://www.steamcardexchange.net/index.php?gamepage-appid-457880/

![DLC](https://i.imgur.com/PyI9DZK.png)

**Comment by Citrinate** [comment]
The cards are now unmarketable
